### ISSUE TITLE
Portalling out of Nether with smaller border than overworld checks the Nether-border for overworld location

### ISSUE THREAD

**Issue by DalBrar** [Brettflan/WorldBorder#167]
My players have been complaining about getting "You have reached the edge of this world" error message when taking a nether portal out of the nether and into the overworld.

This is how I have my borders set:
```
round-border: false
...
  world:
    x: 0.5
    z: 0.5
    radiusX: 20000
    radiusZ: 20000
    wrapping: false
  world_nether:
    x: 0.5
    z: 0.5
    radiusX: 2500
    radiusZ: 2500
    wrapping: false
```

If a player makes a portal in the Nether, say at 75, 435, when they enter the portal they are teleported to 2497, 2497 in the Overworld and told that they have reached the edge of the world. A portal is not created AND sometimes they are even teleported into walls and suffocate and die.

Debug output:
```
12.12 00:35:18 [Server] INFO Teleport cause: NETHER_PORTAL
12.12 00:35:20 [Server] INFO Teleport cause: UNKNOWN
12.12 00:35:20 [Server] WARN Border crossing in "world_nether". Border radius 2500 at X: 0.5 Z: 0.5
12.12 00:35:20 [Server] WARN Player position X: 607.5 Y: 70.2 Z: 3469.2
12.12 00:35:20 [Server] WARN New position in world "world_nether" at X: 607.5 Y: 61.0 Z: 2497.5```

Notice the "New Position" SHOULD BE "world" but instead says "world_nether"

This server is running Paper version git-Paper-235 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
